Models/ActionsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IDEO.Models
{
    public class DeleteViewModel
    {
        public string Name { get; set; }
    }

    public class AddViewModel
    {
        [Required]
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Nazwa węzła")]
        public string ParentName { get; set; }
    }

    public class EditViewModel
    {
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        [Display(Name = "Nowa nazwa")]
        public string NewName { get; set; }

        [Display(Name = "Nazwa węzła")]
        public string ParentName { get; set; }

        [Display(Name = "Nazwa nowego węzła")]
        public string NewParentName { get; set; }
    }
}

Controllers/ActionsController.cs
using IDEO.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace IDEO.Controllers
{
    public class ActionsController : Controller
    {
        private readonly IDEOEntities db = new IDEOEntities();
        private readonly List<string> list = new List<string>();
        private readonly List<string> list2 = new List<string>();
        private bool Status;
        private string message;

        // GET: Add
        public ActionResult Add()
        {
            List<IdeoTree> items = db.IdeoTree.OrderBy(a => a.name).ToList();
            foreach (var i in items)
            {
                list.Add(i.name);
            }
            list.Insert(0, "IDEO TREE");
            ViewBag.Items = list;
            return View(new AddViewModel { ParentName = list[0] });
        }

        // POST: Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddViewModel item)
        {
            List<IdeoTree> items = db.IdeoTree.OrderBy(a => a.name).ToList();
            foreach (var i in items)
            {
                list.Add(i.name);
            }
            list.Insert(0, "IDEO TREE");
            ViewBag.Items = list;
            int parent_id = 0;
            if(item.ParentName != "IDEO TREE")
            {
                var findparentid = db.IdeoTree.First(a => a.name == item.ParentName);
                parent_id = findparentid.id;
            }
            if (ModelState.IsValid)
            {
                if (FindByName(item.Name))
                {
                    message = "Element o podanej nazwie już istnieje w strukturze.";
                }
                else
                {
                    var newitem = new IdeoTree()
                    {
                        name = item.Name,
                        parent_id = parent_id
                    };
                    using(IDEOEntities db = new IDEOEntities()) { 
                    db.IdeoTree.Add(newitem);
                    db.SaveChanges();
                    }
                    message = "Element " + item.Name + " został dodany do struktury.";
                    Status = true;
                }
            }
            else
            {
                message = "Nieprawidłowe żądanie";
                Status = false;
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;
            return View(item);
        }

        // GET: Delete
        public ActionResult Delete()
        {
            List<IdeoTree> items = db.IdeoTree.OrderBy(a => a.name).ToList();
            foreach (var i in items)
            {
                list.Add(i.name);
            }
            ViewBag.Items = list;
            return View();
        }

        // POST: Delete
        [HttpPost]
        public ActionResult Delete(DeleteViewModel item)
        {
            IdeoTree toDelete = db.IdeoTree.SingleOrDefault(a => a.name == item.Name);
            var ParentIdToDelete = db.IdeoTree.Where(a => a.parent_id == toDelete.id);
            db.IdeoTree.Remove(toDelete);
            db.IdeoTree.RemoveRange(ParentIdToDelete);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        // GET: Edit
        public ActionResult Edit()
        {
            List<IdeoTree> items = db.IdeoTree.OrderBy(a => a.name).ToList();
            foreach (var i in items)
            {
                list.Add(i.name);
            }
            list2.Insert(0, "nie zmieniaj");
            list2.Insert(1, "IDEO TREE");
            list2.AddRange(list);
            ViewBag.Items = list;
            ViewBag.Items2 = list2;
            return View();
        }

        // POST: Edit
        [HttpPost]
        public ActionResult Edit(EditViewModel item)
        {
            List<IdeoTree> items = db.IdeoTree.OrderBy(a => a.name).ToList();
            foreach (var i in items)
            {
                list.Add(i.name);
            }
            list2.Insert(0, "nie zmieniaj");
            list2.Insert(1, "IDEO TREE");
            list2.AddRange(list); 
            ViewBag.Items = list;
            ViewBag.Items2 = list2;

            int parent_id;
            if (item.NewParentName == "IDEO TREE")
            {
                parent_id = 0;
            }
            else if (item.NewParentName == "nie zmieniaj")
            {
                var findparentid = db.IdeoTree.First(a => a.name == item.Name);
                parent_id = findparentid.parent_id;
            }
            else
            {
                var findparentid = db.IdeoTree.First(a => a.name == item.NewParentName);
                parent_id = findparentid.id;
            }
            if (ModelState.IsValid)
            {
                if (FindByName(item.NewName))
                {
                    message = "Element o podanej nazwie już istnieje w strukturze.";
                }
                else
                {
                    if (item.NewName == null)
                    {
                        item.NewName = item.Name;
                    }
                    using (IDEOEntities db = new IDEOEntities()) 
                    { 
                        IdeoTree itemtochange = db.IdeoTree.SingleOrDefault(a => a.name == item.Name);
                        if(itemtochange != null) 
                        { 
                            itemtochange.name = item.NewName;
                            itemtochange.parent_id = parent_id;
                            db.SaveChanges();
                            message = "Zmiany zostały zapisane pomyślnie.";
                            Status = true;
                        }
                    }
                }
            }
            else
            {
                message = "Nieprawidłowe żądanie";
                Status = false;
            }
            ViewBag.Message = message;
            ViewBag.Status = Status;

            return View(item);
        }

        internal bool FindByName(string name)
        {
            using (db)
            {
                return db.IdeoTree.Where(x => x.name == name).FirstOrDefault() != null;
            }
        }
    }
}

Views/Actions/Add.cshtml
@model IDEO.Models.AddViewModel
@{
    ViewBag.Title = "Add";
}

<h3>Dodawanie nowego elementu do struktury.</h3>
<hr />

@using (Html.BeginForm("Add", "Actions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
    {
        if (ViewBag.Message != null)
        {
            <div class="alert alert-success">
                <strong>Sukces!</strong> @ViewBag.Message
            </div>
        }
    }
    else
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ParentName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ParentName, new SelectList(ViewBag.Items), new { @class = "col-md-2 control-label", @style = "margin-right:10px" })
                @Html.ValidationMessageFor(m => m.ParentName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-success" value="Dodaj" />
            </div>
        </div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Błąd! </strong>@ViewBag.Message
            </div>
        }
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

Views/Actions/Delete.cshtml
@model IDEO.Models.DeleteViewModel
@{
    ViewBag.Title = "Delete";
}

<h3>Usuwanie elementu struktury. W przypadku wyboru węzła, usunięte zostaną również wszystkie jego liście.</h3>
<hr />

@using (Html.BeginForm("Delete", "Actions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @*<div class="form-group">
        <div class="col-md-offset-1 col-md-10">

            @Html.Label("Element do usunięcia")
            @Html.DropDownListFor(m => m.Name, new SelectList(ViewBag.Items), new { @class = "col-md-2 control-label", @style = "margin-right:10px" })
            <input type="submit" value="Usuń" class="btn btn-danger" />
            @Html.ActionLink("Anuluj", "../Home/Index", null, new { @class = "btn btn-default" })

        </div>
    </div>*@
    <div class="form-group">
        @Html.Label("Element do usunięcia", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.DropDownListFor(m => m.Name, new SelectList(ViewBag.Items), new { @class = "col-md-2 control-label", @style = "margin-right:10px" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Usuń" class="btn btn-danger" />
            @Html.ActionLink("Anuluj", "../Home/Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

Views/Actions/Edit.cshtml
@model IDEO.Models.EditViewModel
@{
    ViewBag.Title = "Edit";
}

<h3>Edycja elementu struktury, zmiana nazwy/przenoszenie do innego węzła.</h3>

@using (Html.BeginForm("Edit", "Actions", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{

    if (ViewBag.Status != null && Convert.ToBoolean(ViewBag.Status))
    {
        if (ViewBag.Message != null)
        {
            <div class="alert alert-success">
                <strong>Sukces!</strong> @ViewBag.Message
            </div>
        }
    }
    else
    {
        @Html.AntiForgeryToken()
        <hr />
        <div class="form-group">
            @Html.Label("Element do edycji", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Name, new SelectList(ViewBag.Items), new { @class = "col-md-2 control-label", @style = "margin-right:10px" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.NewName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.NewName, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.NewName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Nowy węzeł", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.NewParentName, new SelectList(ViewBag.Items2), new { @class = "col-md-2 control-label", @style = "margin-right:10px" })
                @Html.ValidationMessageFor(m => m.NewParentName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-success" value="Zapisz" />
                @Html.ActionLink("Anuluj", "../Home/Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
        if (ViewBag.Message != null)
        {
            <div class="alert alert-danger">
                <strong>Błąd! </strong>@ViewBag.Message
            </div>
        }
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}